// <auto-generated />
using AyisigiApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AyisigiApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231228221322_ProductSeedData")]
    partial class ProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AyisigiApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Ottoman Wedding",
                            ProductPrice = 30000m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Romanian Wedding",
                            ProductPrice = 32000m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Russian Wedding",
                            ProductPrice = 20000m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "French Wedding",
                            ProductPrice = 15000m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Standart Turkish Wedding",
                            ProductPrice = 7000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
