// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace AyisigiApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Wedding"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Party"
                        });
                });

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerPassword")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerMail = "basartuna35@gmail.com",
                            CustomerName = "Tuna",
                            CustomerPassword = 123
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerMail = "ymanbasarbasar@gmail.com",
                            CustomerName = "Hilmi",
                            CustomerPassword = 12345
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "/images/1.png",
                            ProductName = "Ottoman Wedding",
                            ProductPrice = 30000m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "/images/2.png",
                            ProductName = "Romanian Wedding",
                            ProductPrice = 32000m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "/images/3.png",
                            ProductName = "Russian Wedding",
                            ProductPrice = 20000m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "/images/4.png",
                            ProductName = "French Wedding",
                            ProductPrice = 15000m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "/images/5.png",
                            ProductName = "Standart Turkish Wedding",
                            ProductPrice = 7000m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "/images/6.png",
                            ProductName = "Nordic Wedding",
                            ProductPrice = 10000m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "/images/7.png",
                            ProductName = "Chair",
                            ProductPrice = 100m
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
