// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace AyisigiApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Wedding"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Party"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Ottoman Wedding",
                            ProductPrice = 30000m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Romanian Wedding",
                            ProductPrice = 32000m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Russian Wedding",
                            ProductPrice = 20000m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "French Wedding",
                            ProductPrice = 15000m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Standart Turkish Wedding",
                            ProductPrice = 7000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
